src/demo/pages/DemoContainer.jsx
src/lib/components/ui/MultipleSelectField/MultipleSelectField.scss
src/lib/components/ui/SelectField/SelectField.scss
src/lib/styles/settings/_forms-theme.scss
src/lib/styles/tools/forms/_foundation.scss
src/lib/theme.scss

**FF/Windows before:**
**FF/Windows after:**
**Chrome/Windows before:**
**Chrome/Windows after:**
**Chrome/Mac (styling not supported, works well out of the box):**

Better distinct disabled options in Select Fields and Multiple Select Fields

---

src/demo/pages/DemoContainer.jsx
src/lib/components/ui/Card/Card.jsx
src/lib/components/ui/Card/Card.scss
src/lib/components/ui/Card/_theme.scss
src/lib/components/ui/Card/tests/Card.test.jsx
src/lib/components/ui/Card/tests/__snapshots__/Card.test.jsx.snap
src/lib/theme.scss

Add dense option for Card (#39)

---

src/demo/pages/DemoContainer.jsx
src/lib/components/ui/Modal/Modal.jsx
src/lib/components/ui/Modal/Modal.scss

Add auto size option for Modal (#51)

---

src/demo/pages/DemoContainer.jsx
src/demo/pages/navigation.js
src/lib/styles/settings/_utilities.scss

Add text color utility classes (#64)

---

src/lib/components/screens/Login/__tests__/__snapshots__/ForgotPassword.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/Login.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/NewPassword.test.jsx.snap
src/lib/components/ui/Button/Button.jsx
src/lib/components/ui/Button/tests/__snapshots__/Button.test.jsx.snap
src/lib/components/ui/CheckboxField/CheckboxField.jsx
src/lib/components/ui/CheckboxField/tests/__snapshots__/CheckboxField.test.jsx.snap
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/components/ui/MultipleSelectField/MultipleSelectField.jsx
src/lib/components/ui/MultipleSelectField/tests/__snapshots__/MultipleSelectField.test.jsx.snap
src/lib/components/ui/Radio/Radio.jsx
src/lib/components/ui/Radio/tests/__snapshots__/Radio.test.jsx.snap
src/lib/components/ui/SelectField/SelectField.jsx
src/lib/components/ui/SelectField/tests/__snapshots__/SelectField.test.jsx.snap
src/lib/components/ui/TextArea/TextArea.jsx
src/lib/components/ui/TextArea/tests/__snapshots__/TextArea.test.jsx.snap
src/lib/components/ui/TextField/TextField.jsx
src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
src/lib/components/ui/Toggle/Toggle.jsx
src/lib/components/ui/Toggle/tests/__snapshots__/Toggle.test.jsx.snap

Basic patterns used everywhere:
Native elements <input|textarea|button|checkbox|select|..> = id
Label element <label> = id__label
Real label value = id__labelText
Description text = id__descriptionText
Helper text = id__helperText
Error text = id__errorText

Improve IDs of UI elements (#89)

---

src/lib/components/layout/CTA/__tests__/CTA.test.jsx
src/lib/components/layout/CTA/__tests__/__snapshots__/CTA.test.jsx.snap
src/lib/components/layout/CardList/CardList.scss
src/lib/components/layout/CardList/__tests__/CardList.test.jsx
src/lib/components/layout/CardList/__tests__/__snapshots__/CardList.test.jsx.snap
src/lib/components/layout/FormLayout/FormLayout.scss
src/lib/components/layout/FormLayout/__tests__/FormLayout.test.jsx
src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
src/lib/components/layout/List/__tests__/List.test.jsx
src/lib/components/layout/List/__tests__/__snapshots__/List.test.jsx.snap
src/lib/components/layout/Media/__tests__/Media.test.jsx
src/lib/components/layout/Media/__tests__/__snapshots__/Media.test.jsx.snap
src/lib/components/layout/Row/__tests__/Row.test.jsx
src/lib/components/layout/Row/__tests__/__snapshots__/Row.test.jsx.snap
src/lib/components/layout/Toolbar/__tests__/Toolbar.test.jsx
src/lib/components/layout/Toolbar/__tests__/ToolbarGroup.test.jsx
src/lib/components/layout/Toolbar/__tests__/__snapshots__/Toolbar.test.jsx.snap
src/lib/components/layout/Toolbar/__tests__/__snapshots__/ToolbarGroup.test.jsx.snap

It tells more than simple `div`s and `span`s.

Use real intended components in snapshot tests of layout components

---

src/demo/pages/DemoContainer.jsx
src/lib/components/ui/Button/Button.scss
src/lib/components/ui/Modal/Modal.jsx
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap

Remove automatic margins from `Button`s in favour of `Toolbar` layout

---

src/demo/pages/DemoContainer.jsx
src/lib/components/ui/Alert/Alert.jsx
src/lib/components/ui/Alert/Alert.scss
src/lib/components/ui/Alert/_mixins.scss
src/lib/components/ui/Alert/_theme.scss
src/lib/components/ui/Alert/_variables.scss
src/lib/components/ui/Alert/tests/Alert.test.jsx
src/lib/components/ui/Alert/tests/__snapshots__/Alert.test.jsx.snap
src/lib/components/ui/Modal/__tests__/Modal.test.jsx
src/lib/theme.scss
src/lib/translation/TranslationContext.jsx

Make `Alert`s dismissible (#11)

---

src/demo/pages/DemoContainer.jsx
src/lib/components/ui/Card/Card.scss
src/lib/components/ui/Card/_theme.scss
src/lib/theme.scss

Add opacity to disabled `Card`s (#61)

---

src/lib/components/ui/Modal/Modal.jsx
src/lib/components/ui/Modal/Modal.scss
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/components/ui/Modal/_theme.scss
src/lib/theme.scss

Limit width of auto-sized Modal (#106)

---

.editorconfig
.markdownlintrc
LICENSE.md
README.md
package-lock.json
package.json

Let's make the “coding style” of markdown files consistent. Let's try the default settings first and see. There might be a later adjustment of line wrapping rules which have been subject to discussion recently.

Lint markdown files to enforce consistent writing and reading experience

---

demo/index.html
package.json

Ttrack docs with GA, improve project meta data

---

src/lib/components/ui/Alert/Alert.scss
src/lib/components/ui/Alert/_mixins.scss
src/lib/components/ui/Alert/_theme.scss
src/lib/components/ui/Alert/_variables.scss
src/lib/theme.scss

Enhance theme options for `Alert`.

Make `Alert`'s font weight and stripe customisable

---

.github/pr-labeler.yml
.github/release-drafter.yml
.github/workflows/release-management.yml
CONTRIBUTING.md
README.md
RELEASING.md

Check for version change before attempting to publish a release draft

---

.github/pr-labeler.yml
CONTRIBUTING.md
src/gatsby-theme-docz/wrapper.js

Track docs visits with Google Analytics (#166)

---

src/lib/components/ui/Button/_mixins.scss

Allow wrapping of `Button` labels (#181)

---

src/lib/components/ui/Button/Button.jsx
src/lib/components/ui/ButtonGroup/ButtonGroup.jsx
src/lib/components/ui/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
src/lib/components/ui/CheckboxField/CheckboxField.jsx
src/lib/components/ui/Radio/Radio.jsx
src/lib/components/ui/SelectField/SelectField.jsx
src/lib/components/ui/TextArea/TextArea.jsx
src/lib/components/ui/TextField/TextField.jsx
src/lib/components/ui/Toggle/Toggle.jsx
src/lib/utils/__tests__/transferProps.test.js
src/lib/utils/transferProps.js

Simplify syntax of transferred props (#88)

---

src/lib/styles/tools/_forms.deprecated.scss
src/lib/utils/transferProps.js

- Fix mentioned form fields
- Improve `transferProps()` function

Fix misaligned help and validation texts of `CheckboxField`, `Radio` and `Toggle` inside `FormLayout`

---

src/lib/components/ui/Button/_tools.scss
src/lib/components/ui/Table/Table.scss
src/lib/styles/tools/_transition.scss
src/lib/styles/tools/forms/_foundation.scss

Purpose of this change is to disallow performance-heavy transitions and to turn off motion if users prefer so.
Closes #137.

Validate transitions and honor user's `prefers-reduced-motion` settings (#137)

---

src/lib/components/ui/Modal/Modal.jsx
src/lib/components/ui/Modal/Modal.scss
src/lib/components/ui/Modal/README.mdx
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/components/ui/Modal/_theme.scss
src/lib/theme.scss

Introduce `Modal` position option (#213)

---

src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
src/lib/components/ui/Button/Button.jsx
src/lib/components/ui/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
src/lib/components/ui/CheckboxField/CheckboxField.jsx
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/components/ui/SelectField/SelectField.jsx
src/lib/components/ui/Table/__tests__/__snapshots__/Table.test.jsx.snap
src/lib/components/ui/TextArea/TextArea.jsx
src/lib/components/ui/TextField/TextField.jsx
src/lib/components/ui/Toggle/Toggle.jsx
src/lib/provider/__tests__/__snapshots__/RUIProvider.test.jsx.snap

Change UI component exports to fix `withForwardedRef` (#229)

---

.github/workflows/git.yml
.github/workflows/pull-request-meta.yml
.github/workflows/release-management.yml
.github/workflows/test.yml

Upgrade GitHub actions: setup-node and upload/download-artifact

---

src/lib/components/layout/FormLayout/README.mdx
src/lib/components/ui/CheckboxField/CheckboxField.jsx
src/lib/components/ui/CheckboxField/__tests__/__snapshots__/CheckboxField.test.jsx.snap
src/lib/components/ui/Radio/Radio.jsx
src/lib/components/ui/Toggle/Toggle.jsx
src/lib/components/ui/Toggle/__tests__/__snapshots__/Toggle.test.jsx.snap
src/lib/styles/tools/form-fields/_inline-field-layout.scss

Extend `FormLayout` demo with field layout switch to prevent similar bugs in future.

Fix `CheckboxField` and `Toggle` breaking vertical `FormLayout` (#249)

---

src/lib/components/ui/ScrollView/README.mdx
src/lib/components/ui/ScrollView/ScrollView.scss

Restrict scrolling of `ScrollView` to single direction at a time (#233)

---

.github/workflows/test.yml

Reduce CI test runs as they are already triggered on every push to the PR branch

---

src/docs/getting-started/usage.mdx

Claim support for controlled components only

---

.markdownlint.jsonc
CONTRIBUTING.md
doczrc.js
src/docs/contribute/composition.mdx
src/docs/contribute/css.mdx

New sections:
- Contribute > Composition
- Contribute > CSS Guidelines
A PR with refactored CSS to match the new guidelines will follow as soon as #301 is merged.

Document composition principles and CSS guidelines

---

.github/workflows/release-management.yml

According to the migration guide of `JamesIves/github-pages-deploy-action`: https://github.com/JamesIves/github-pages-deploy-action/discussions/592

Update dependencies of the release workflow

---

src/docs/foundation/accessibility.mdx
src/lib/components/Button/README.mdx
src/lib/components/ButtonGroup/README.mdx
src/lib/components/CTA/README.mdx
src/lib/components/Card/README.mdx
src/lib/components/CheckboxField/README.mdx
src/lib/components/FormLayout/README.mdx
src/lib/components/Link/README.mdx
src/lib/components/List/README.mdx
src/lib/components/Modal/README.mdx
src/lib/components/Paper/README.mdx
src/lib/components/Radio/README.mdx
src/lib/components/ScrollView/README.mdx
src/lib/components/SelectField/README.mdx
src/lib/components/Table/README.mdx
src/lib/components/Tabs/README.mdx
src/lib/components/Toggle/README.mdx
src/lib/components/Toolbar/README.mdx

Relates to #329 (bug introduced) and #337 (partial fix).

Fix broken links in docs

---

src/docs/css-helpers/box-alignment.mdx
src/lib/styles/settings/_utilities.scss

Most notable is the addition of responsive alignment classes for flex/grid items.

Extend box alignment helper classes to cover more use cases with `Grid` and flex helper

---

package-lock.json
package.json
src/lib/components/ButtonGroup/README.mdx
src/lib/components/FormLayout/README.mdx
src/lib/components/Modal/Modal.jsx
src/lib/components/Popover/Popover.jsx
src/lib/components/Popover/Popover.scss
src/lib/components/Popover/PopoverWrapper.jsx
src/lib/components/Popover/README.mdx
src/lib/components/Popover/__tests__/Popover.test.jsx
src/lib/components/Popover/__tests__/PopoverWrapper.test.jsx
src/lib/components/Popover/_helpers/getRootAlignmentClassName.js
src/lib/components/Popover/_helpers/getRootSideClassName.js
src/lib/components/Popover/_theme.scss
src/lib/components/Popover/index.js
src/lib/components/Text/README.mdx
src/lib/components/Toolbar/README.mdx
src/lib/index.js
src/lib/theme.scss
webpack.config.js

Visit https://floating-ui.com/docs/react-dom to learn how to integrate.
---
Closes #45.

Introduce `Popover` component (#45)

---

package-lock.json

Update supported browser versions

---

src/lib/components/ScrollView/ScrollView.jsx
src/lib/components/ScrollView/__tests__/ScrollView.test.jsx

Add support for ref forwarding in ScrollView (#406)

---

.github/workflows/broken-links-check.yml

Fixes [this error](https://github.com/react-ui-org/react-ui/actions/runs/3257721390/jobs/5349194353):

Bypass robots.txt when automatically checking availability of external links in the docs

---

src/lib/components/Table/_components/TableCell.scss
src/lib/components/Table/_components/TableHeaderCell/TableHeaderCell.jsx

Improve the design of `Table` with sorting buttons

---

src/gatsby-theme-docz/theme/prism/light.js
src/lib/components/ButtonGroup/README.mdx
src/lib/components/FormLayout/README.mdx
src/lib/components/Modal/README.mdx
src/lib/components/Popover/README.mdx
src/lib/components/Table/_components/TableCell.scss
src/lib/components/Table/_components/TableHeaderCell/TableHeaderCell.jsx
src/lib/components/Text/README.mdx
src/lib/components/Toolbar/README.mdx
src/lib/styles/theme-constants/_colors.scss
src/lib/theme.scss

Improve the default theming of `secondary` and `selected` colors of `Button`

---

src/lib/components/Modal/README.mdx

Clarify how `Modal` and `FormLayout` can be composed together

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release-management.yml
.github/workflows/test.yml
docker/mkdocs/Dockerfile
docker/node/Dockerfile
package-lock.json
package.json

Require Node 18 (current LTS) (#374)

---

.github/markdown-link-check.json
.github/workflows/broken-links-check.yml
.github/workflows/external-links-check.yml
.github/workflows/test.yml

There are two link checks now:
- This check is performed during every PR and only checks **absolute** URLs in all **Markdown files**.
- There is still the existing broken links check that checks **all** links at **react-ui.io**.

Check all Markdowns for broken links

---

src/docs/getting-started/usage.md

Update Usage instructions according to the current state of things (#197)

---

src/styles/elements/_page.scss

Developers want to handle this themselves. Let us not be overly opinionated.
Closes #523.

Do not set any dimensions of `<html>` and `<body>` elements (#523)

---

src/components/Button/README.md

Improve docs in relation to using icon only buttons (#489)

---

.github/workflows/release-management.yml
src/CNAME

Fix MkDocs deployment to GitHub pages (#556)

---

CODEOWNERS

Should be solved in https://github.com/react-ui-org/react-ui/issues/632

Partially disable code owners to enable merge during someone's time off
