react-ui-org/react-ui

src/demo/pages/DemoContainer.jsx
src/lib/components/ui/Modal/Modal.jsx
src/lib/components/ui/Modal/Modal.scss
src/lib/components/ui/Modal/__tests__/Modal.test.jsx
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/components/ui/Modal/_theme.scss
src/lib/components/ui/Modal/_variables.scss
src/lib/theme.scss

- Added `small` and `large` options through `size` prop.
- Slightly decreased the default `medium` size from 46 to 40 rem to better fit other sizes so the scale is now 20 rem / 40 rem / 60 rem.
Closes #40.

Add size option for Modal (#40)

---

src/lib/styles/settings/_breakpoints.scss
src/lib/theme.scss

Closes #54. The largest breakpoints aren't actually used anywhere in RUI so the change doesn't affect anything else.

Improve breakpoint scale (#54)

---

.github/workflows/git.yml
.github/workflows/test.yml

Block merge of fixup commits (#75)

---

src/lib/components/screens/Login/__tests__/__snapshots__/ForgotPassword.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/Login.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/NewPassword.test.jsx.snap
src/lib/components/ui/MultipleSelectField/MultipleSelectField.scss
src/lib/components/ui/SelectField/SelectField.scss
src/lib/components/ui/TextArea/TextArea.scss
src/lib/components/ui/TextField/TextField.jsx
src/lib/components/ui/TextField/TextField.scss
src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
src/lib/styles/tools/forms/_foundation.scss
src/lib/styles/tools/forms/_layouts.scss
src/lib/theme.scss

- Prevent form field helper text from taking up more space than necessary when input size is smaller than default
- Wrap validation message in horizontal form field layout to prevent unwanted shift of adjacent elements when the message shows up
- Improve readability of helper text in horizontal `Text Field` when input size is too small
Closes #46.
**Before:**
**After:**

Fix helper texts in horizontal form fields

---

src/demo/pages/DemoContainer.jsx
src/lib/components/layout/CTA/CTA.scss
src/lib/components/layout/Toolbar/Toolbar.jsx
src/lib/components/layout/Toolbar/Toolbar.scss
src/lib/components/layout/Toolbar/ToolbarGroup.jsx
src/lib/components/layout/Toolbar/__tests__/Toolbar.test.jsx
src/lib/components/layout/Toolbar/__tests__/ToolbarGroup.test.jsx
src/lib/components/layout/Toolbar/__tests__/__snapshots__/Toolbar.test.jsx.snap
src/lib/components/layout/Toolbar/__tests__/__snapshots__/ToolbarGroup.test.jsx.snap
src/lib/components/layout/Toolbar/_theme.scss
src/lib/components/ui/Modal/Modal.jsx
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/theme.scss

- Add `dense` option to `Toolbar`
- Make `dense` and `nowrap` options available also for `ToolbarGroup`

Enhance `Toolbar` and `Toolbar Group`

---

src/lib/components/screens/Login/__tests__/__snapshots__/ForgotPassword.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/Login.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/NewPassword.test.jsx.snap
src/lib/components/ui/TextField/TextField.jsx
src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
src/lib/styles/settings/_forms-theme.scss
src/lib/styles/settings/_forms.scss
src/lib/styles/tools/forms/_foundation.scss
src/lib/styles/tools/forms/_sizes.scss
src/lib/theme.scss

- Limit width of form fields to prevent overflowing their container (closes #102)
- Handle custom input size with CSS to fix different behaviour across browsers (closes #101)

Improve form field sizing

---

src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap
src/lib/components/ui/ScrollView/ScrollView.jsx
src/lib/components/ui/ScrollView/ScrollView.scss
src/lib/components/ui/ScrollView/__tests__/__snapshots__/ScrollView.test.jsx.snap

It's not in the demo but it's possible:
~~Removing the `overflow: hidden` rule made it necessary to refactor the `Modal` layout.~~
Closes #128.

Enable `ScrollView` arrows to overflow the `ScrollView` area (#128)

---

src/lib/components/layout/FormLayout/FormLayoutCustomField.jsx
src/lib/components/layout/FormLayout/FormLayoutCustomField.scss
src/lib/components/layout/FormLayout/__tests__/FormLayoutCustomField.test.jsx
src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayoutCustomField.test.jsx.snap
src/lib/styles/tools/forms/_layouts.scss

This is now possible (`Alert` is able to fill available width):

Enable `FormLayoutCustomField` to be full-width

---

src/lib/components/screens/Login/__tests__/__snapshots__/ForgotPassword.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/Login.test.jsx.snap
src/lib/components/screens/Login/__tests__/__snapshots__/NewPassword.test.jsx.snap
src/lib/components/ui/Button/Button.jsx
src/lib/components/ui/Button/_base.scss
src/lib/components/ui/Button/tests/__snapshots__/Button.test.jsx.snap
src/lib/components/ui/Modal/__tests__/__snapshots__/Modal.test.jsx.snap

It was broken and it's fixed 🤷‍♂️. Seriously, there was a problem with loading icon overflowing the button when only icon is shown. Solved by hiding the original icon when loading:

Fix icon-only buttons in loading state

---

src/lib/components/ui/MultipleSelectField/MultipleSelectField.scss
src/lib/components/ui/SelectField/SelectField.scss
src/lib/components/ui/TextArea/TextArea.scss
src/lib/components/ui/TextField/TextField.scss
src/lib/styles/tools/forms/_foundation.scss

The text alignment of form field labels could have been affected by a parent. This is now fixed.

Don't let form fields' text alignment be affected by a parent

---

src/demo/pages/DemoContainer.jsx
src/lib/components/layout/List/List.jsx
src/lib/components/layout/List/List.scss
src/lib/components/layout/List/__tests__/List.test.jsx
src/lib/components/layout/List/__tests__/__snapshots__/List.test.jsx.snap

The heading "Right-aligned List" doesn't make sense but 1) RTL readiness is now just an under-the-hood preparation, and 2) the demo will disappear soon anyway. The shift of mindset to the RTL-aware API is the more important thing here.
Closes #84.

BC: Make `List` RTL ready (#84)

---

src/lib/components/layout/CardList/__tests__/__snapshots__/CardList.test.jsx.snap
src/lib/components/ui/Card/Card.jsx
src/lib/components/ui/Card/Card.scss
src/lib/components/ui/Card/_mixins.scss
src/lib/components/ui/Card/_theme.scss
src/lib/components/ui/Card/tests/Card.test.jsx
src/lib/components/ui/Card/tests/__snapshots__/Card.test.jsx.snap
src/lib/theme.scss

It makes a better sense when we don't mix borders and colors in a single prop.
Closes #138.

BC: Split `Card` types and variants in separate props and add more variants

---

src/lib/components/ui/ScrollView/ScrollView.jsx
src/lib/components/ui/Table/__tests__/Table.test.jsx
src/lib/styles/settings/_utilities.scss

I'm just adding a couple of new `display` utility classes because I was expecting them when I was writing the docs (#15) and they weren't there. I think that our future users could think the same.

Extend utilities

---

.github/pr-labeler.yml
.github/release-drafter.yml
.github/workflows/pr-labeler.yml
.github/workflows/release-management.yml
.github/workflows/test.yml
CONTRIBUTING.md
README.md
RELEASING.md
doczrc.js
package-lock.json

Automate releasing and publishing to npm

---

src/lib/components/layout/FormLayout/FormLayout.jsx
src/lib/components/layout/FormLayout/FormLayout.scss
src/lib/components/layout/FormLayout/FormLayoutCustomField.jsx
src/lib/components/layout/FormLayout/FormLayoutCustomField.scss
src/lib/components/layout/FormLayout/README.mdx
src/lib/components/layout/FormLayout/__tests__/FormLayout.test.jsx
src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayout.test.jsx.snap
src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayoutCustomField.test.jsx.snap
src/lib/styles/settings/_forms-theme.scss
src/lib/styles/tools/_forms.deprecated.scss
src/lib/styles/tools/forms/_foundation.scss
src/lib/styles/tools/forms/_layouts.scss
src/lib/theme.scss

Refactor styles to make use of `display: contents` which just works. Fallback values are no longer necessary. 🎉

Make `auto` and `limited` label widths of horizontal `FormLayout` work in all browsers (#135)

---

src/lib/components/ui/Card/Card.jsx
src/lib/components/ui/Card/CardBody.jsx
src/lib/components/ui/Card/CardFooter.jsx
src/lib/components/ui/Card/README.mdx
src/lib/components/ui/Card/__tests__/CardBody.test.jsx
src/lib/components/ui/Card/__tests__/CardFooter.test.jsx

Introduce `Card` use case with `ScrollView` (#178)

---

.eslintrc
package-lock.json
src/gatsby-theme-docz/wrapper.js
src/lib/components/layout/CTA/README.mdx
src/lib/components/layout/FormLayout/FormLayout.jsx
src/lib/components/layout/FormLayout/README.mdx
src/lib/components/layout/Grid/Grid.jsx
src/lib/components/layout/Grid/Grid.scss
src/lib/components/layout/Grid/GridSpan.jsx
src/lib/components/layout/Grid/README.mdx
src/lib/components/layout/Grid/__tests__/GridSpan.test.jsx
src/lib/components/layout/Grid/__tests__/__snapshots__/GridSpan.test.jsx.snap
src/lib/components/layout/Grid/_mixins.scss
src/lib/components/layout/Grid/_theme.scss
src/lib/components/layout/Grid/helpers/__tests__/generateResponsiveCustomProperties.test.js
src/lib/components/layout/Grid/helpers/generateResponsiveCustomProperties.js
src/lib/components/layout/Grid/index.js
src/lib/components/layout/List/README.mdx
src/lib/components/layout/Media/README.mdx
src/lib/components/layout/Toolbar/README.mdx
src/lib/components/ui/Card/README.mdx
src/lib/index.js
src/lib/styles/settings/_breakpoints.scss
src/lib/theme.scss

Extend `Grid` layout with custom rows and columns options and more (#149)

---

src/lib/components/layout/Grid/Grid.jsx
src/lib/components/layout/Grid/Grid.scss
src/lib/components/layout/Grid/README.mdx
src/lib/theme.scss

It's necessary to be able to restore original behaviour in our project.

Extend `Grid` layout with responsive alignment options (#193)

---

doczrc.js
src/gatsby-theme-docz/index.css
src/gatsby-theme-docz/theme/prism/dark.js
src/gatsby-theme-docz/theme/prism/light.js
src/lib/styles/elements/_code.scss
src/lib/styles/theme/_code.scss
src/lib/theme.scss

Code font family and font size are now customizable.
These settings are also reflected in docs where the code block appearance has been unified and slightly tweaked to work better with bigger font size of the docs.

Make code font family and font size customizable

---

doczrc.js

Live code examples are now collapsed by default to make docs easier to scan:

Collapse Playground code by default

---

src/lib/components/layout/Toolbar/Toolbar.scss

The problem:
The fix (that 1px space comes from calculation rounding in the checkbox itself):

Get rid of unwanted spacing of inline elements placed in `Toolbar`

---

src/docs/customize/theming/forms.mdx
src/docs/foundation/accessibility.mdx
src/lib/components/ui/Alert/Alert.scss
src/lib/components/ui/Alert/README.mdx
src/lib/components/ui/CheckboxField/CheckboxField.scss
src/lib/components/ui/Modal/Modal.scss
src/lib/components/ui/Radio/Radio.scss
src/lib/components/ui/ScrollView/ScrollView.scss
src/lib/components/ui/Toggle/Toggle.scss
src/lib/styles/theme/_accessibility.scss
src/lib/styles/theme/_form-fields.scss
src/lib/styles/tools/_accessibility.scss
src/lib/styles/tools/form-fields/_box-field-layout.scss
src/lib/styles/tools/form-fields/_inline-field-elements.scss
src/lib/theme.scss
webpack.config.js

Improve accessibility for touch screens.
Keep in mind that form field labels and help texts are also always interactive. Tap target just increases interactive area around the input itself.
Closes #234.

Define minimum tap target size for interactive elements (#234)

---

src/lib/components/ui/FileInputField/FileInputField.jsx
src/lib/components/ui/FileInputField/FileInputField.scss
src/lib/components/ui/FileInputField/README.mdx
src/lib/components/ui/FileInputField/__tests__/FileInputField.test.jsx
src/lib/components/ui/FileInputField/__tests__/__snapshots__/FileInputField.test.jsx.snap
src/lib/components/ui/FileInputField/index.js
src/lib/components/ui/TextArea/README.mdx
src/lib/components/ui/TextField/README.mdx
src/lib/index.js
src/lib/styles/theme/_accessibility.scss
src/lib/styles/tools/_accessibility.scss
webpack.config.js

Create `FileInputField` component (#219)

---

src/lib/styles/tools/form-fields/_box-field-layout.scss
src/lib/styles/tools/form-fields/_inline-field-elements.scss
src/lib/theme.scss

⚠️ Breaking change, you may need to multiply your calculations by `1rem`.

Use unitless line height to take advantage of inheritance

---

src/docs/foundation/spacing.mdx
src/lib/components/layout/CTA/CTA.scss
src/lib/components/layout/FormLayout/FormLayout.scss
src/lib/components/layout/FormLayout/README.mdx
src/lib/components/layout/Grid/Grid.scss
src/lib/components/layout/List/List.scss
src/lib/components/layout/Media/Media.scss
src/lib/components/layout/Toolbar/README.mdx
src/lib/components/layout/Toolbar/Toolbar.scss
src/lib/components/ui/Modal/Modal.scss
src/lib/components/ui/Modal/_settings.scss
src/lib/components/ui/ScrollView/README.mdx
src/lib/styles/generic/_shared.scss
src/lib/styles/settings/_layouts.scss
src/lib/styles/theme/_spacing.scss
src/lib/styles/tools/_spacing.scss
src/lib/theme.scss

Separate shared bottom spacings into categories with configurable values.
New theming options:
- `--rui-spacing-bottom-default`
- `--rui-spacing-bottom-headings`
- `--rui-spacing-bottom-layouts`
Closes #180.

Remove bottom margin from last-child elements (#180)

---

src/lib/components/layout/FormLayout/FormLayoutCustomField.jsx
src/lib/components/layout/FormLayout/FormLayoutCustomField.scss
src/lib/components/layout/FormLayout/README.mdx
src/lib/components/layout/FormLayout/__tests__/FormLayoutCustomField.test.jsx
src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayoutCustomField.test.jsx.snap
src/lib/styles/settings/_form-fields.scss
webpack.config.js

New options:
- `disabled`
- `innerFieldSize`
- `labelForId`
- `required`
- `validationState`
Closes #174.

Extend `FormLayoutCustomField` options to improve accessibility and design consistency (#174)

---

src/docs/customize/theming/forms.mdx
src/lib/components/layout/FormLayout/FormLayoutCustomField.jsx
src/lib/components/layout/FormLayout/FormLayoutCustomField.scss
src/lib/components/layout/FormLayout/README.mdx
src/lib/components/layout/FormLayout/__tests__/FormLayoutCustomField.test.jsx
src/lib/components/layout/FormLayout/__tests__/__snapshots__/FormLayoutCustomField.test.jsx.snap
src/lib/styles/settings/_form-fields.scss
src/lib/styles/theme/_form-fields.scss
src/lib/styles/tools/form-fields/_box-field-layout.scss
src/lib/theme.scss
webpack.config.js

This change enables adjusting vertical alignment of label and field (individually) in horizontal form field layouts, including horizontal `FormLayout`.
⚠️ Renamed custom properties:
- `--rui-form-field-horizontal-label-alignment` → `--rui-form-field-horizontal-label-text-align`
New custom properties:
- `--rui-form-field-horizontal-label-vertical-alignment`
- `--rui-form-field-horizontal-field-vertical-alignment`
- `--rui-form-field-horizontal-label-padding-y` (optional)
Closes #173.

Add vertical alignment options for horizontal form fields (#173)

---

src/lib/components/ui/Card/README.mdx
src/lib/components/ui/Paper/Paper.jsx
src/lib/components/ui/Paper/Paper.scss
src/lib/components/ui/Paper/README.mdx
src/lib/components/ui/Paper/__tests__/Paper.test.jsx
src/lib/components/ui/Paper/__tests__/__snapshots__/Paper.test.jsx.snap
src/lib/components/ui/Paper/_theme.scss
src/lib/components/ui/Paper/index.js
src/lib/index.js
src/lib/theme.scss

Extract `Paper` from `Card` as dicussed in https://github.com/react-ui-org/react-ui/pull/278#issuecomment-857576378.

Introduce `Paper` component as a primary option to hold larger content areas

---

src/docs/_components/Placeholder/Placeholder.jsx
src/docs/_components/Placeholder/Placeholder.scss
src/lib/components/layout/Toolbar/README.mdx
src/lib/components/ui/Text/README.mdx
src/lib/components/ui/Text/Text.jsx
src/lib/components/ui/Text/Text.scss
src/lib/components/ui/Text/__tests__/Text.test.jsx
src/lib/components/ui/Text/__tests__/__snapshots__/Text.test.jsx.snap
src/lib/components/ui/Text/helpers/getRootHyphensClassName.js
src/lib/components/ui/Text/helpers/getRootWordWrappingClassName.js
src/lib/components/ui/Text/index.js
src/lib/index.js

Introduce `Text` component to control wrapping of text content (#286)

---

src/lib/components/layout/Toolbar/README.mdx

Warn about known `Toolbar` limitations in docs

---

src/lib/components/ui/TextField/README.mdx
src/lib/components/ui/TextField/TextField.jsx
src/lib/components/ui/TextField/TextField.scss
src/lib/components/ui/TextField/__tests__/__snapshots__/TextField.test.jsx.snap
src/lib/styles/settings/_form-fields.scss
src/lib/styles/tools/form-fields/_box-field-elements.scss

Re-introduce custom input size for numeric inputs (#281)

---

src/docs/css-helpers/typography.mdx
src/lib/components/layout/CTA/README.mdx
src/lib/components/layout/FormLayout/README.mdx
src/lib/components/layout/Toolbar/README.mdx
src/lib/components/ui/Button/Button.jsx
src/lib/components/ui/Button/README.mdx
src/lib/components/ui/Button/__tests__/Button.test.jsx
src/lib/components/ui/Button/_base.scss
src/lib/components/ui/Button/_settings.scss
src/lib/components/ui/Button/_tools.scss
src/lib/components/ui/Button/helpers/getRootLabelVisibilityClassName.js
src/lib/styles/tools/_accessibility.scss

Extend `Button`'s `labelVisibility` with breakpoints (#273)

---

src/lib/components/CTA/CTA.jsx
src/lib/components/Card/Card.jsx
src/lib/components/FormLayout/FormLayout.jsx
src/lib/components/Media/Media.jsx
src/lib/components/Tabs/Tabs.jsx

Ease PropType validation of the `children` prop to allow passing in nonrenderable `false` and `null` values (#332)

---

src/lib/components/TextField/TextField.jsx
src/lib/components/TextField/__tests__/TextField.test.jsx

Fixing a bug caused by accidental line deletion introduced in PR #318.
Line deletion is [not present in the diff](https://github.com/react-ui-org/react-ui/pull/318/files#diff-cbad86635207378f7dc7cf04fa71f5f3dd595b1a546d8c4ac73ade4998e71687L43).
However, it [is present in the final commit](https://github.com/react-ui-org/react-ui/commit/986356f815862e9d97f68f45c8447f2b64b9b41b#diff-cbad86635207378f7dc7cf04fa71f5f3dd595b1a546d8c4ac73ade4998e71687L43) (screenshot from SourceTree).

Fix custom input size of `TextField`

---

src/lib/components/Grid/Grid.scss

So doing a fix like this is no longer necessary:
```css
/* Reset list padding until fixed in RUI. */
.root > ul {
padding-left: 0;
}
```

Fix undesired offset of `Grid` when rendered as `dl`, `ol`, or `ul`

---

src/docs/foundation/typography.mdx
src/lib/components/Alert/_settings.scss
src/lib/components/Button/README.mdx
src/lib/components/Button/_settings.scss
src/lib/components/Button/_theme.scss
src/lib/components/Button/_tools.scss
src/lib/styles/theme/_typography.scss
src/lib/theme.scss

New theming options:
- `--rui-typography-line-height-small`
- `--rui-Button--small__padding-y`
- `--rui-Button--medium__padding-y`
- `--rui-Button--large__padding-y`
Before:
After:

Vertically expand `Button`s with long labels to prevent overflow

---

src/docs/customize/theming/forms.mdx
src/lib/components/Button/README.mdx
src/lib/theme.scss

Useful for typical use case of input and button in row.

Link sizes of box form fields to `Button` sizes to make customisation easier

---

src/lib/components/CheckboxField/CheckboxField.jsx
src/lib/components/CheckboxField/CheckboxField.scss
src/lib/components/FormLayout/README.mdx
src/lib/components/Radio/Radio.scss
src/lib/components/Toggle/Toggle.jsx
src/lib/components/Toggle/Toggle.scss
src/lib/styles/tools/_reset.scss
src/lib/styles/tools/form-fields/_box-field-layout.scss
src/lib/styles/tools/form-fields/_inline-field-elements.scss
src/lib/styles/tools/form-fields/_inline-field-layout.scss

Affects `CheckboxField` and `Toggle`.
Closes #323.

Display labels of inline form fields in the same `FormLayout` column as other labels (#323)

---

src/lib/components/Toolbar/Toolbar.scss
src/lib/styles/tools/_spacing.scss
src/lib/theme.scss

⚠️ Visual result remains the same, but it's necessary to **revisit margins** of neighboring elements in downstream projects.
Closes #333.

Refactor `Toolbar` to use `gap` property for spacing between items (#333)

---

src/lib/components/Grid/README.mdx
src/lib/components/Grid/_theme.scss
src/lib/theme.scss

Keep only theming options related to other design tokens. The main reason of the change is to ensure stack is always the default outcome of `Grid` and it cannot be changed through theming (only through global props which is the recommended way).
Relates to #308.

Reduce `Grid` theming API in favour of global props

---

src/lib/components/Tabs/TabsItem.scss

Item border color disappeared during CSS minification:
A shorthand for `border` was generated which made the final rule with four colors invalid.
Before:
After:

Fix `Tabs` border color

---

doczrc.js
src/lib/components/Modal/Modal.scss
src/lib/components/Modal/ModalBody.jsx
src/lib/components/Modal/ModalBody.scss
src/lib/components/Modal/ModalContent.scss
src/lib/components/Modal/ModalFooter.scss
src/lib/components/Modal/ModalHead.jsx
src/lib/components/Modal/ModalHead.scss
src/lib/components/Modal/ModalTitle.jsx
src/lib/components/Modal/ModalTitle.scss
src/lib/components/Modal/README.mdx
src/lib/components/Modal/__tests__/ModalBody.test.jsx
src/lib/components/Modal/__tests__/ModalTitle.test.jsx
src/lib/components/Modal/_helpers/getScrollingClassName.js
src/lib/components/Modal/_settings.scss
src/lib/components/Modal/_theme.scss
src/lib/components/Modal/index.js
src/lib/components/ScrollView/ScrollView.scss
src/lib/index.js
src/lib/theme.scss
webpack.config.js

- Enhance `Modal` scrolling modes
- Redesign `Modal` introducing new theming options
- Introduce `ModalTitle` component to better handle default modal title styling
Relates to issue #306 and PR #387.
- `--rui-Modal__padding-x`
- `--rui-Modal__padding-y`
- `--rui-Modal__separator__width`
- `--rui-Modal__separator__color`

Redesign `Modal` introducing `ModalTitle` and new theming options (#306)

---

src/lib/components/ScrollView/README.mdx
src/lib/components/ScrollView/ScrollView.jsx
src/lib/components/ScrollView/ScrollView.scss
src/lib/components/ScrollView/__tests__/ScrollView.test.jsx
src/lib/components/ScrollView/_theme.scss
src/lib/theme.scss

Removed custom properties:
- `--rui-ScrollView__arrow__initial-offset` in favour of `prevArrowInitialOffset` and `nextArrowInitialOffset`
- `--rui-ScrollView__shadow__initial-offset` in favour of `startShadowInitialOffset` and `endShadowInitialOffset`
Closes #303.

Rewrite `ScrollView` API to limit the number of customization approaches (#303)

---

src/lib/components/Modal/README.mdx

Document pitfalls of combining horizontal `FormLayout` with small `Modal` (#386)

---

src/lib/components/Radio/Radio.jsx
src/lib/components/Radio/__tests__/Radio.test.jsx
src/lib/components/SelectField/README.mdx
src/lib/components/SelectField/SelectField.jsx
src/lib/components/SelectField/__tests__/SelectField.test.jsx
src/lib/components/SelectField/_components/Option/Option.jsx
src/lib/components/SelectField/_components/Option/index.js

Add support for `<optgroup>` to the `Select` component (#395)

---

src/docs/contribute/api.mdx
src/lib/components/Grid/Grid.jsx
src/lib/components/Grid/README.mdx
src/lib/components/Grid/__tests__/Grid.test.jsx
src/lib/components/Grid/_helpers/__tests__/generateResponsiveCustomProperties.test.js
src/lib/components/Grid/_helpers/generateResponsiveCustomProperties.js

For `columnGap` and `rowGap`, reduce all values (responsive or not) in the format `var(--rui-spacing-X)` to corresponding numbers (just `X`), e.g.:
```jsx
// Before
<Grid columnGap="var(--rui-spacing-3)">
// After
<Grid columnGap={3}>
```
(Please mind the correct value type.)
Closes #402.

Limit `Grid` gap props to accept only available spacing values (#402)

---

src/lib/components/Button/Button.jsx
src/lib/components/Button/README.mdx
src/lib/components/CheckboxField/CheckboxField.jsx
src/lib/components/CheckboxField/README.mdx
src/lib/components/FileInputField/FileInputField.jsx
src/lib/components/FileInputField/README.mdx
src/lib/components/Modal/ModalCloseButton.jsx
src/lib/components/Popover/Popover.jsx
src/lib/components/Popover/README.mdx
src/lib/components/ScrollView/README.mdx
src/lib/components/ScrollView/ScrollView.jsx
src/lib/components/SelectField/README.mdx
src/lib/components/SelectField/SelectField.jsx
src/lib/components/TextArea/README.mdx
src/lib/components/TextArea/TextArea.jsx
src/lib/components/TextField/README.mdx
src/lib/components/TextField/TextField.jsx
src/lib/components/Toggle/README.mdx
src/lib/components/Toggle/Toggle.jsx

Fix console warning due to using ref in PropTypes just for documentation (#426)

---

src/docs/foundation/accessibility.mdx
src/lib/components/Button/_tools.scss
src/lib/styles/theme/_accessibility.scss
src/lib/theme.scss

- Do not mix hover and focus style on `Button`.
- Make it possible to keep the original box shadow of the component on focus.

Fix `Button` appearance on focus

---

doczrc.js
src/docs/customize/theming/overview.mdx
src/docs/foundation/accessibility.mdx
src/docs/foundation/colors.mdx
src/docs/foundation/design-tokens.mdx
src/docs/foundation/spacing.mdx
src/lib/components/Modal/ModalCloseButton.scss
src/lib/styles/theme-constants/_colors.scss
src/lib/styles/theme/_links.scss
src/lib/theme.scss

Set global and semantic tokens apart and improve the documentation.
⚠️ **Breaking changes:**
- Renamed link color tokens from `--rui-color-action-link(-*)` to `--rui-color-text-link(-*)`.
- Removed internal design token `--rui-ratio-disabled-cursor` in favour of `--rui-cursor-not-allowed`.

Improve the structure of global and semantic design tokens and explain how they are related

---

src/lib/components/Button/Button.jsx
src/lib/components/Button/_base.scss
src/lib/components/Button/_priorities.scss
src/lib/components/ButtonGroup/__tests__/ButtonGroup.test.jsx
src/lib/components/FormLayout/README.mdx
src/lib/components/FormLayout/__tests__/FormLayout.test.jsx
src/lib/components/InputGroup/InputGroup.jsx
src/lib/components/InputGroup/InputGroup.scss
src/lib/components/InputGroup/InputGroupContext.js
src/lib/components/InputGroup/README.mdx
src/lib/components/InputGroup/__tests__/InputGroup.test.jsx
src/lib/components/InputGroup/_theme.scss
src/lib/components/InputGroup/index.js
src/lib/components/SelectField/SelectField.jsx
src/lib/components/SelectField/SelectField.scss
src/lib/components/TextField/TextField.jsx
src/lib/components/TextField/TextField.scss
src/lib/index.js
src/lib/styles/tools/form-fields/_box-field-layout.scss
src/lib/theme.scss
webpack.config.js

Any suggestions, especially regarding CSS and documentation, are warmly welcome. @adamkudrna 
Build failed due to asset size limit. I will not change the limit for now as it is solved in simultaneous pull requests which will be probably merged before this one.
Closes #430

Create `InputGroup` component (#430)

---

.github/pr-labeler.yml

So it's easier to switch between projects for the developers.

Automatically mark PRs with `task/*` branches as features

---

.browserslistrc
package-lock.json

```sh
npx browserslist
and_chr 116
and_ff 116
chrome 116
chrome 115
edge 116
edge 115
firefox 117
firefox 116
firefox 115
firefox 102
ios_saf 16.5
ios_saf 16.4
ios_saf 16.3
ios_saf 16.2
ios_saf 16.1
ios_saf 16.0
safari 16.6
safari 16.5
safari 16.4
safari 16.3
safari 16.2
safari 16.1
safari 16.0
```

Narrow down supported browsers in Browserslist config according to the docs

---

CODEOWNERS

Define who is responsible for code in this repository.
Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

Introduce `CODEOWNERS` file to define responsibility for code in the repository

---

src/components/Modal/Modal.jsx
src/components/Modal/README.md
src/components/Modal/_hooks/useModalScrollPrevention.js

Allow the `Modal` component to block scrolling on any HTML element instead of just the `<body>` element (#472)

---

src/components/FormLayout/README.md
src/components/InputGroup/InputGroup.scss
src/components/Radio/Radio.scss
src/styles/tools/form-fields/_box-field-layout.scss

Subgrid is now supported in all major browsers including Chrome and Edge joining as last in August's version 117. However, there is some fieldset/legend magic that prevents subgrid from being used on `<fieldset>` element (as per the spec (sic!), the magic adds an additional virtual box which breaks the subgrid).
As a result, subgrid cannot be used on `<fieldset>` elements until the following Chromium issue is resolved:
https://bugs.chromium.org/p/chromium/issues/detail?id=1473242
Closes #493

Fix `Radio` and `InputGroup` in horizontal `FormLayout` in Chrome and Edge (#493)

---

src/components/Radio/README.md
src/components/Radio/Radio.jsx

Move `transferProps` back from `fieldset` to `input` in `RadioField` (#481)

---

.markdownlint.jsonc
src/components/Button/README.md
src/components/Card/README.md
src/components/Modal/README.md

- Use 4 spaces to indent nested lists in MD so MkDocs can render them correctly (#486)
- Fix `Modal` previews not being rendered because of a misplaced comment
Closes #486.

Use 4 spaces to indent nested lists in MD so MkDocs can render them correctly (#486)

---

src/docs/_overrides/main.html

Install the latest version of `docoff` that no longer establishes new stacking context within previews.
Closes #471.

Fix `Modal` previews being overlapped by MkDocs header (#471)

---

src/docs/_assets/stylesheets/extra.css

This seems to be the easiest workaround.
See: https://bugs.webkit.org/show_bug.cgi?id=229816
Closes #506.

Intentionally omit patch version in Prism CSS URL due to parsing bug in Safari (#506)

---

mkdocs.yml
src/docs/_assets/stylesheets/extra.css
src/docs/_overrides/main.html

Config seems to be the better place — unless we need the additional `<script>` attributes like `crossorigin` or `type`. @mbohal Do we need them? There is no warning in console and everything seems to be working.

Move mkDocs CSS and JS resource calls from template to config

---

src/components/InputGroup/InputGroup.jsx
src/components/InputGroup/InputGroup.scss
src/components/InputGroup/README.md
src/components/InputGroup/__tests__/InputGroup.test.jsx

Make InputGroup label reflect required prop (#510)

---

.markdownlint.jsonc

* rules were sorted
* `MD013` is used instead of `line-length` because we use codes everywhere else
* `MD024` was titghtened to allow duplicate headings only under different parents

Update markdownlint rules

---

package.json
webpack.config.babel.js

In order to allow the consuming apps to leverage friendly CSS class names and React tooling (PropTypes, StrictMode, etc.) during development this commit adds development builds of CSS and JS files into the `dist` folder.

Make both production and development builds available

---

CONTRIBUTING.md
package.json

- Create `.env` file automatically after `npm install` (don't overwrite if already exists)
- Improve contributing instructions so it's easier to find what to run where

Create `.env` file automatically after `npm install` (don't overwrite if already exists)

---

mkdocs.yml
src/docs/_assets/stylesheets/extra.css

Also, previously used production builds do not exist until `npm run build` is run for the first time.

Use development CSS and JS in docs to improve code readability

---

mkdocs.yml
src/components/Alert/README.md
src/components/Badge/README.md
src/components/Button/README.md
src/components/ButtonGroup/README.md
src/components/Card/README.md
src/components/CheckboxField/README.md
src/components/FileInputField/README.md
src/components/FormLayout/README.md
src/components/Grid/README.md
src/components/InputGroup/README.md
src/components/Modal/README.md
src/components/Paper/README.md
src/components/Popover/README.md
src/components/Radio/README.md
src/components/ScrollView/README.md
src/components/SelectField/README.md
src/components/Table/README.md
src/components/Tabs/README.md
src/components/Text/README.md
src/components/TextArea/README.md
src/components/TextField/README.md
src/components/TextLink/README.md
src/components/Toggle/README.md
src/components/Toolbar/README.md

The page listing react synthetic events became legacy and was moved to https://legacy.reactjs.org/docs/events.html
I could not find a direct replacement, the closes thing I found is https://react.dev/reference/react-dom/components/common#common-props. This page however is not HTML element specific and thus I think it better to link do MDN even though there some differences (e.g. `class` vs `className`)
Also I have updated transferProps based on the new doc page.

Omit link to legacy list of React synthetic events in component documentation

---

src/components/ScrollView/ScrollView.scss
src/components/Tabs/Tabs.scss

Use the `clip` value for `overflow` to prevent the content from unwanted scrolling on the cross axis during keyboard navigation.
https://github.com/react-ui-org/react-ui/assets/5614085/bd81a4c0-53b1-4196-ad8d-fa97512abeb8
Closes #499.

Prevent `Tabs` and `ScrollView` from unwanted cross-axis scrolling during keyboard navigation #499

---

README.md
src/docs/getting-started/usage.md
src/index.js

As a result of #440, component styles are no longer part of the JS bundle. They reside in the extracted `react-ui[.development].css` file. Therefore:
1. **The Sass scenario is not supported now.** Importing just the `theme.scss`, `foundation.scss` and `helpers.scss` makes no sense. Users still have to load the entire CSS bundle which is the only way to get components styles, and it already contains those global style layers.
2. To allow tree shaking, more steps need to be taken from our side.
Closes #517.

Correct the documentation of CSS usage

---

.eslintrc
src/components/_helpers/__tests__/transferProps.test.js
src/components/_helpers/transferProps.js

PR Description:
Changes Made:
Removed the console.log statement from the codebase to improve code cleanliness and prevent unnecessary logging. Additionally, added a linting rule to disallow console.log statements unless explicitly allowed by an eslint-disable statement.
Reasoning:
Removing console.log statements helps maintain a clean codebase and prevents clutter in the console output. By enforcing a linting rule to disallow console.log statements, we ensure consistency in code quality and adherence to best practices.
Impact:
Enhances code readability and maintainability by removing unnecessary logging statements.
Helps prevent accidental logging of sensitive information in production environments.
Encourages developers to use more robust debugging techniques, such as using breakpoints …

#532 Fix/forgottent console log in dev mode

---

src/docs/customize/global-props.md
src/provider/RUIProvider.jsx
src/provider/__tests__/RUIProvider.test.jsx
src/utils/__tests__/mergeDeep.js
src/utils/mergeDeep.js

Introduce usage of nested `RUIProvider` (#541)

---

src/components/CheckboxField/CheckboxField.jsx
src/components/CheckboxField/README.md
src/components/FileInputField/FileInputField.jsx
src/components/FileInputField/README.md
src/components/InputGroup/InputGroup.jsx
src/components/Radio/README.md
src/components/Radio/Radio.jsx
src/components/SelectField/README.md
src/components/SelectField/SelectField.jsx
src/components/TextArea/README.md
src/components/TextArea/TextArea.jsx
src/components/TextField/README.md
src/components/TextField/TextField.jsx
src/components/Toggle/README.md
src/components/Toggle/Toggle.jsx

Allow form fields' `label` to accept any node (#526)

---

.github/workflows/release-management.yml
mkdocs.yml

- Handle GitHub release publishing with `gh` CLI
- Replace deprecated MkDocs Material extension
Closes #531.

Handle GitHub release publishing with `gh` CLI (#531)

---

mkdocs.yml
src/docs/foundation/collections.md
src/docs/foundation/colors.md
src/docs/foundation/design-tokens.md
src/styles/settings/_collections.scss

This is a prerequisite for #492 and #468.

Introduce color collections for generative styling of components

---

src/components/Badge/Badge.jsx
src/components/Badge/Badge.module.scss
src/components/Badge/__tests__/Badge.test.jsx
src/components/Button/Button.jsx
src/components/ButtonGroup/ButtonGroup.jsx
src/components/_helpers/getRootPriorityClassName.js

⚠️  This change affects output HTML and may break downstream snapshot tests.

Make `Badge` priority class always present like in all other components

---

src/components/Alert/__tests__/Alert.test.jsx
src/components/Badge/Badge.jsx
src/components/Badge/Badge.module.scss
src/components/Badge/README.md
src/components/Badge/__tests__/Badge.test.jsx
src/components/Badge/_settings.scss
src/components/Button/__tests__/Button.test.jsx
src/components/Card/__tests__/Card.test.jsx
src/styles/tools/_collections.scss
src/styles/tools/_string.scss
src/theme.scss
tests/propTests/feedbackColorPropTest.js
tests/propTests/neutralColorPropTest.js

`Badge` color variants are now generated using color collections.
Other components to be styled the same way already support theming,
so `Badge` needs to support theming too.
New theming options:
`--rui-Badge--<PRIORITY>--<COLOR>__<PROPERTY>`
See `theme.scss` for all available options.

Introduce theming of `Badge` color variants

---

src/components/Popover/Popover.module.scss
src/components/Popover/_theme.scss
webpack.config.babel.js

Because of rendering quirks sometimes a line can appear between the popover and arrow
(more visible on low dpi displays)
This pr fixes that by moving the arrow 1px down

Fix rendering glitch of `Popover` arrow on low-dpi displays

---

src/components/Grid/Grid.module.scss
src/styles/tools/form-fields/_box-field-layout.scss

Intentionally use longhand properties because custom property fallback mechanism evaluates `initial` values as empty. That makes the other value of the shorthand property unexpectedly used for both axes.
Introduced in #550. Closes #569.

Fix `Grid` items/content alignment when just a single value is set (#569)

---

src/components/_helpers/resolveContextOrProp.js

Allows boolean props to propagate when layout context is false
Closes #567

Fix layout context prop resolving for boolean types (#567)

---

src/components/InputGroup/InputGroup.module.scss

Since form inputs can have a fixed minimum size (and they have it by default), `InputGroup` should overflow horizontally if its content doesn't fit the available width. This limits the usage of `InputGroup` in narrow containers and on mobile screens at the moment, but prevents a bug when components inside a shrinked `InputGroup` would overlap each other.
Closes #522.

Let wide `InputGroup`s honor the minimum input width and overflow horizontally (#522)

---

src/components/Alert/Alert.module.scss
src/components/Alert/README.md
src/styles/elements/_links.scss
src/styles/theme/_links.scss
src/theme.scss

~~Default font weight of links is now set to "regular" so it is consistent with other links in React UI. However, it remains configurable because of downstream project requirements.~~
Links in `Alert` now inherit the font weight which is consistent with other links in React UI.
Since the color inheritance for links has been introduced in #492, links in e.g. validation messages cannot be distinguished from regular text until hovered. We chose to underline all text links by default to make those links discoverable by users.
Closes #577

Make text links underlined by default #577

---

src/components/Alert/Alert.module.scss
src/components/Alert/README.md
src/components/Card/Card.module.scss
src/components/Card/README.md
src/components/CheckboxField/README.md
src/components/TextField/README.md
src/components/TextLink/README.md
src/components/TextLink/_theme.scss
src/components/Toggle/README.md
src/styles/elements/_links.scss
src/styles/theme/_form-fields.scss
src/styles/theme/_links.scss
src/styles/tools/_collections.scss
src/styles/tools/form-fields/_variants.scss
src/theme.scss
webpack.config.babel.js

⚠️ BREAKING CHANGES:
- For `Alert` and `Card`, link color changes by component variant.
- For all input components, link color changes by validation state.
See #492.

Inherit link color in components using the Feedback color collection (#492)

---

src/components/Popover/Popover.jsx
src/components/Popover/Popover.module.scss
src/components/Popover/README.md

Using the Popover API with the help of a helper element this implements a native way to create a popover that closes and opens on button and backdrop click.

Add controlled popover

---

src/components/CheckboxField/CheckboxField.jsx
src/components/CheckboxField/README.md
src/components/CheckboxField/__tests__/CheckboxField.test.jsx
src/components/Radio/README.md
src/components/Radio/Radio.jsx
src/components/Radio/Radio.module.scss
src/components/Radio/__tests__/Radio.test.jsx
src/components/SelectField/README.md
src/components/SelectField/SelectField.jsx
src/components/SelectField/__tests__/SelectField.test.jsx
src/components/Toggle/README.md
src/components/Toggle/Toggle.jsx
src/components/Toggle/__tests__/Toggle.test.jsx
src/docs/customize/theming/forms.md
src/styles/tools/form-fields/_foundation.scss
tests/propTests/renderAsRequiredPropTest.js

Users may find themselves in a situation where the input is not required (i.e. making the input checked), but they also don't want to render the field as optional because not choosing an option can be perfectly valid. For this case, there is the `renderAsRequired` prop.
This affects `CheckboxField`, `Radio`, `SelectField`, and `Toggle`.
Closes #487.

Allow check fields and selectable fields to render as required #487

---

src/components/Popover/Popover.jsx
src/components/Popover/README.md
src/components/Popover/_helpers/cleanPlacementStyle.js

Fix misplaced Popover when using Floating UI (#566)

---

.github/workflows/broken-links-check.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/external-links-check.yml
.github/workflows/git.yml
.github/workflows/lint.yml
.github/workflows/pull-request-meta.yml
.github/workflows/release-management.yml
.github/workflows/test.yml
docker/node/Dockerfile

This is required by upcoming pull request as Ubuntu 20.04 is old and generates incorrect snapshots as latest Playwright Docker Image uses Ubuntu 24.04.

Update Github Workflows to use Ubuntu 24.04

---

src/components/Modal/Modal.jsx
src/components/Modal/Modal.module.scss
src/components/Modal/ModalBody.module.scss
src/components/Modal/ModalFooter.module.scss
src/components/Modal/ModalHeader.module.scss
src/components/Modal/README.md
src/components/Modal/__tests__/Modal.test.jsx
src/components/Modal/_settings.scss
src/docs/foundation/collections.md
src/theme.scss

- `Modal` can now be colored via the `color` prop, using a value from the Feedback Colors collection.
New custom properties in shape of `--rui-Modal--<COLOR>__<PROPERTY>` have been introduced where:
- `<COLOR>` is a value from supported color collections (check the docs to see which collections are supported),
- `<PROPERTY>` is one of `border-color` or `background-color`.
- Add description of our color collections so it's clearer when they can be used.
Closes #468.

Introduce `color` property to the `Modal` component (#468)

---

src/components/Alert/Alert.jsx
src/components/Alert/README.md
src/components/Alert/__tests__/Alert.test.jsx
src/components/Alert/_settings.scss
src/components/Card/Card.jsx
src/components/Card/Card.module.scss
src/components/Card/README.md
src/components/Card/__tests__/Card.test.jsx
src/components/Card/_settings.scss
src/components/Card/_theme.scss
src/docs/foundation/collections.md
src/styles/tools/_collections.scss
src/theme.scss

We found the Neutral Colors collection insufficiently flexible to use, so we are removing it from more complex components where its usage was unclear and confusing.
Features:
- New `--rui-Card__background-color` custom property has been introduced to define `Card`'s default background color.
Breaking changes:
- `Alert`: light and dark colors (Neutral Colors collection) have been dropped with no replacement.
- `Card`: light color now corresponds to the default appearance. The dark color option has been dropped with no replacement.
Migration:
- `Alert`: pick another color from the Feedback Colors collection.
- `Card`: remove `color="light"` to keep the default light appearance. If using `color="dark"`, pick another color from the Feedback Colors collection.
Closes #615.

Drop Neutral Colors collection from `Alert` and `Card` (#615)

---

src/components/FileInputField/FileInputField.jsx
src/components/FileInputField/FileInputField.module.scss
src/components/FileInputField/README.md
src/components/FileInputField/__tests__/FileInputField.test.jsx
src/components/FileInputField/_settings.scss
src/components/FormLayout/README.md
src/components/InputGroup/InputGroup.module.scss
src/components/InputGroup/README.md
src/components/Modal/README.md
src/styles/elements/_links.scss
src/styles/generic/_focus.scss
src/styles/theme/_form-fields.scss
src/styles/tools/_accessibility.scss
src/styles/tools/_links.scss
src/styles/tools/form-fields/_box-field-elements.scss
src/styles/tools/form-fields/_box-field-layout.scss
src/styles/tools/form-fields/_box-field-sizes.scss
src/styles/tools/form-fields/_variants.scss
src/translations/en.js
webpack.config.babel.js

Introduce custom design of `FileInputField` (#244)

---

README.md
RELEASING.md
mkdocs.yml
package.json
src/docs/_assets/stylesheets/extra.css
src/docs/contribute/composition.md
src/docs/contribute/css.md
src/docs/customize/font.md
src/docs/foundation/typography.md
src/docs/getting-started/usage.md
src/theme.scss

It ensures that the text is displayed in the font that the user is most comfortable with, and it also reduces the size of the data transferred.
Breaking change:
The Titillium web font has been replaced with native font stack.
Migration:
To keep the Titillium web font in your project, load the web font and override the `--rui-font-family-base` custom property:
```
--rui-font-family-base: 'Titillium Web', helvetica, roboto, arial, sans-serif;
```
Closes #417.

Use native font stack (#417)

---

src/components/Card/Card.module.scss
src/components/Card/README.md
src/components/Card/_theme.scss
src/theme.scss

New `--rui-Card__border-color` custom property has been introduced to define Card's default border color.
The default value is border primary, so `Card`s are now bordered by default to be distinguishable on default `Paper`.
Before:
After:

Introduce border color theming option for default `Card`

---

src/components/FileInputField/FileInputField.jsx

Fix `FileInputField` not resetting properly on `reset` event inside of a form

Fix `FileInputField` not resetting properly (#627)

---

src/components/Modal/Modal.jsx
src/components/Modal/_helpers/dialogOnClickHandler.js

The modal would close when the user selected something outside the modal and ended the selection outside of the modal.

Fix modal closing when selection ended outside of the modal (#645)

---

src/components/ScrollView/ScrollView.jsx
src/components/ScrollView/_hooks/useScrollPositionHook.js

ScrollView would not update if the size of the content changed due to style or window size changes.
ScrollView would get stuck in a state where the arrows would not update when the user scrolled fast back and forth.

Fix `ScrollView` scroll position issues (#501)
